import {
  AnalyticsUpIcon,
  ArrowRight01Icon,
  BarChartIcon,
  Bookmark01Icon,
  BrainIcon,
  Calendar01Icon,
  CallIcon,
  CameraVideoIcon,
  ChartIcon,
  CheckmarkCircle01Icon,
  Clock01Icon,
  CloudIcon,
  CodeIcon,
  CpuIcon,
  DashboardSquare01Icon,
  Database01Icon,
  DnaIcon,
  Download01Icon,
  FileIcon,
  FlashIcon,
  Globe02Icon,
  HeadphonesIcon,
  HeartCheckIcon,
  LaborIcon,
  LaptopIcon,
  Layers01Icon,
  Link01Icon,
  Location01Icon,
  LockIcon,
  MailIcon,
  MicroscopeIcon,
  News01Icon,
  PuzzleIcon,
  Refresh01Icon,
  Rocket01Icon,
  SearchIcon,
  Settings01Icon,
  Shield01Icon,
  ShieldIcon,
  StarIcon,
  Tag01Icon,
  Upload01Icon,
  UserGroupIcon,
  UserIcon,
  ZapIcon,
} from "@hugeicons/core-free-icons";
import type { IconSvgElement } from "@hugeicons/react";

export const iconMap: Record<string, IconSvgElement> = {
  // From navbar-data.ts
  "analytics-up": AnalyticsUpIcon,
  brain: BrainIcon,
  "camera-video": CameraVideoIcon,
  chart: ChartIcon,
  dna: DnaIcon,
  file: FileIcon,
  "heart-check": HeartCheckIcon,
  labor: LaborIcon,
  mail: MailIcon,
  microscope: MicroscopeIcon,
  news: News01Icon,
  shield: ShieldIcon,
  "user-group": UserGroupIcon,
  user: UserIcon,
  // From features-grid/icon-map.tsx
  "bar-chart": BarChartIcon,
  code: CodeIcon,
  cpu: CpuIcon,
  database: Database01Icon,
  flash: FlashIcon,
  globe: Globe02Icon,
  layers: Layers01Icon,
  lock: LockIcon,
  sync: Refresh01Icon,
  settings: Settings01Icon,
  "shield-01": Shield01Icon,
  // From search-data.ts
  cloud: CloudIcon,
  dashboard: DashboardSquare01Icon,
  headphones: HeadphonesIcon,
  laptop: LaptopIcon,
  search: SearchIcon,
  // Broader selection (verified in @hugeicons/core-free-icons)
  "arrow-right": ArrowRight01Icon,
  bookmark: Bookmark01Icon,
  calendar: Calendar01Icon,
  call: CallIcon,
  check: CheckmarkCircle01Icon,
  clock: Clock01Icon,
  download: Download01Icon,
  link: Link01Icon,
  location: Location01Icon,
  puzzle: PuzzleIcon,
  rocket: Rocket01Icon,
  star: StarIcon,
  tag: Tag01Icon,
  upload: Upload01Icon,
  zap: ZapIcon,
};
