[build]
builder = "RAILPACK"
buildCommand = "bun run generate:types && bun run generate:importmap && bun run generate:field-map && bun run build"

[deploy]
startCommand = "bun --bun run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
