/**
 * Generate the field map from Payload block schemas.
 * Run: bun scripts/generate-field-map.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { BentoBlock } from "../src/payload/block-schemas/Bento";
import { CinematicCtaBlock } from "../src/payload/block-schemas/CinematicCta";
import { FaqBlock } from "../src/payload/block-schemas/Faq";
import { HeroBlock } from "../src/payload/block-schemas/Hero";
import { ImageGalleryBlock } from "../src/payload/block-schemas/ImageGallery";
import { LatestArticlesBlock } from "../src/payload/block-schemas/LatestArticles";
import { PricingBlock } from "../src/payload/block-schemas/Pricing";
import { SplitMediaBlock } from "../src/payload/block-schemas/SplitMedia";
import { TestimonialsBlock } from "../src/payload/block-schemas/Testimonials";
import { TrustBlock } from "../src/payload/block-schemas/Trust";
import { introspectBlocks } from "../src/payload/lib/field-map/generate";

const blocks = [
  HeroBlock,
  BentoBlock,
  SplitMediaBlock,
  TestimonialsBlock,
  ImageGalleryBlock,
  LatestArticlesBlock,
  CinematicCtaBlock,
  PricingBlock,
  FaqBlock,
  TrustBlock,
];

const { fieldMap, blockMeta } = introspectBlocks(blocks);

const outDir = resolve(import.meta.dir, "../src/generated");
mkdirSync(outDir, { recursive: true });

const content = `// Auto-generated by scripts/generate-field-map.ts — do not edit
import type { BlockMetaMap, FieldMap } from "@/payload/lib/field-map/types";

export const fieldMap: FieldMap = ${JSON.stringify(fieldMap, null, 2)} as const;

export const blockMeta: BlockMetaMap = ${JSON.stringify(blockMeta, null, 2)} as const;
`;

writeFileSync(resolve(outDir, "field-map.ts"), content);
console.log(`Generated src/generated/field-map.ts (${blocks.length} blocks)`);
