/**
 * Story generator — reads block-fixtures.ts and writes blocks.stories.tsx
 *
 * Run: bun .storybook/generate.ts
 * Called automatically by `bun storybook` and `bun storybook:build`
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { blockFixtures } from "../src/components/blocks/__fixtures__/block-fixtures";

const OUTPUT = resolve(
  import.meta.dirname,
  "../src/components/blocks/__fixtures__/blocks.stories.tsx"
);

// Convert blockType to PascalCase story name
function toPascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const blockTypes = Object.keys(blockFixtures);

// Build the generated file content
let code = `// AUTO-GENERATED by .storybook/generate.ts — do not edit
import type { Meta, StoryObj } from "@storybook/react";
import { renderBlock } from "../render-blocks";
import { blockFixtures } from "./block-fixtures";

type BlockStory = StoryObj<typeof meta>;

const meta = {
  title: "Blocks",
  parameters: { layout: "fullscreen" },
} satisfies Meta;

export default meta;

`;

for (const blockType of blockTypes) {
  const name = toPascal(blockType);

  // Default variant
  code += `export const ${name}: BlockStory = {
  name: "${name} / Default",
  render: () => renderBlock(blockFixtures.${blockType} as any),
};\n\n`;

  // Dark variant
  code += `export const ${name}Dark: BlockStory = {
  name: "${name} / Dark",
  render: () => renderBlock(blockFixtures.${blockType} as any),
  globals: { theme: "dark" },
};\n\n`;

  // Mobile variant
  code += `export const ${name}Mobile: BlockStory = {
  name: "${name} / Mobile",
  render: () => renderBlock(blockFixtures.${blockType} as any),
  parameters: {
    viewport: { defaultViewport: "mobile" },
  },
};\n\n`;
}

writeFileSync(OUTPUT, code, "utf-8");
console.log(
  `Generated ${String(blockTypes.length * 3)} stories for ${String(blockTypes.length)} blocks → ${OUTPUT}`
);
