/**
 * Story generator — reads block-fixtures.ts and writes one story file per category
 *
 * Run: bun .storybook/generate.ts
 * Called automatically by `bun storybook` and `bun storybook:build`
 *
 * Controls: Each story uses `args` so Storybook's Controls panel lets you
 * edit props interactively — just like editing fields in Payload admin.
 * Blocks with select/variant fields get explicit dropdown controls via argTypes.
 *
 * Sidebar structure:
 *   Blocks/
 *     Heroes/       — Hero, Hero Centered, Hero Minimal, Hero Stats
 *     Content/      — Features Grid, Bento, Split Media, ...
 *     Social Proof/ — Testimonials, Team, Trust, Logo Cloud
 *     CTAs/         — CTA Band, Cinematic CTA
 *     Commerce/     — Pricing, FAQ
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  blockArgTypes,
  blockFixtures,
} from "../src/components/blocks/__fixtures__/block-fixtures";
import { BLOCK_CATEGORIES as CATEGORIES } from "../src/components/blocks/block-categories";

const OUT_DIR = resolve(
  import.meta.dirname,
  "../src/components/blocks/__fixtures__"
);

// Convert blockType to readable display name
// heroMinimal → Hero Minimal
function toDisplayName(s: string): string {
  return (s.charAt(0).toUpperCase() + s.slice(1)).replace(
    /([a-z])([A-Z])/g,
    "$1 $2"
  );
}

// Convert blockType to valid JS identifier
function toExportName(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// Check if a block has custom argTypes defined
function hasArgTypes(blockType: string): boolean {
  return blockType in blockArgTypes;
}

// ─── Group blocks by category ─────────────────────────
const grouped = new Map<string, string[]>();
for (const blockType of Object.keys(blockFixtures)) {
  const category = CATEGORIES[blockType] || "Other";
  if (!grouped.has(category)) {
    grouped.set(category, []);
  }
  grouped.get(category)?.push(blockType);
}

// ─── Generate one story file per category ─────────────
let totalStories = 0;
const generatedFiles: string[] = [];

mkdirSync(OUT_DIR, { recursive: true });

for (const [category, blocks] of grouped) {
  const filename = `${category.toLowerCase().replace(/\s+/g, "-")}.stories.tsx`;
  const filepath = resolve(OUT_DIR, filename);

  const isHeroes = category === "Heroes";
  const renderFn = isHeroes ? "renderHeroBlock" : "renderBlock";

  let code = `// AUTO-GENERATED by .storybook/generate.ts — do not edit
import type { Meta, StoryObj } from "@storybook/react";
import { ${renderFn} } from "../render-blocks";
import { blockArgTypes, blockFixtures } from "./block-fixtures";

const meta = {
  title: "Blocks/${category}",
  tags: ["autodocs"],
  parameters: { layout: "fullscreen" },
  // Pass fixture props as args so Storybook Controls panel works —
  // you can edit headings, subtext, variants, etc. just like in Payload admin
  render: (args: Record<string, unknown>) => ${renderFn}(args as any),
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

`;

  for (const blockType of blocks) {
    const exportName = toExportName(blockType);
    const displayName = toDisplayName(blockType);
    const argTypesLine = hasArgTypes(blockType)
      ? `\n  argTypes: blockArgTypes.${blockType} as any,`
      : "";

    // One story per block — use toolbar to toggle dark mode and viewport
    code += `export const ${exportName}: Story = {
  name: "${displayName}",
  args: { ...blockFixtures.${blockType} },${argTypesLine}
};\n\n`;

    totalStories += 1;
  }

  writeFileSync(filepath, code, "utf-8");
  generatedFiles.push(filename);
}

console.log(
  `Generated ${String(totalStories)} stories across ${String(generatedFiles.length)} files for ${String(Object.keys(blockFixtures).length)} blocks`
);
for (const f of generatedFiles) {
  console.log(`  → ${f}`);
}
