// AUTO-GENERATED by .storybook/generate.ts — do not edit
import type { Meta, StoryObj } from "@storybook/react";
import { renderBlock } from "../render-blocks";
import { blockArgTypes, blockFixtures } from "./block-fixtures";

const meta = {
  title: "Blocks/Content",
  tags: ["autodocs"],
  parameters: { layout: "fullscreen" },
  // Pass fixture props as args so Storybook Controls panel works —
  // you can edit headings, subtext, variants, etc. just like in Payload admin
  render: (args: Record<string, unknown>) => renderBlock(args as any),
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

export const FeaturesGrid: Story = {
  name: "Features Grid",
  args: { ...blockFixtures.featuresGrid },
};

export const Bento: Story = {
  name: "Bento",
  args: { ...blockFixtures.bento },
};

export const SplitMedia: Story = {
  name: "Split Media",
  args: { ...blockFixtures.splitMedia },
};

export const ImageGallery: Story = {
  name: "Image Gallery",
  args: { ...blockFixtures.imageGallery },
};

export const LatestArticles: Story = {
  name: "Latest Articles",
  args: { ...blockFixtures.latestArticles },
};

export const RichTextContent: Story = {
  name: "Rich Text Content",
  args: { ...blockFixtures.richTextContent },
  argTypes: blockArgTypes.richTextContent as any,
};

export const TabbedContent: Story = {
  name: "Tabbed Content",
  args: { ...blockFixtures.tabbedContent },
};

export const Timeline: Story = {
  name: "Timeline",
  args: { ...blockFixtures.timeline },
};

export const FormEmbed: Story = {
  name: "Form Embed",
  args: { ...blockFixtures.formEmbed },
  argTypes: blockArgTypes.formEmbed as any,
};

