/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    categories: Category;
    articles: Article;
    'ba-sessions': BaSession;
    'ba-accounts': BaAccount;
    'ba-verifications': BaVerification;
    'ba-two-factors': BaTwoFactor;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'ba-sessions': BaSessionsSelect<false> | BaSessionsSelect<true>;
    'ba-accounts': BaAccountsSelect<false> | BaAccountsSelect<true>;
    'ba-verifications': BaVerificationsSelect<false> | BaVerificationsSelect<true>;
    'ba-two-factors': BaTwoFactorsSelect<false> | BaTwoFactorsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      optimizeVideo: TaskOptimizeVideo;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Profile photo displayed on blog articles
   */
  avatar?: (number | null) | Media;
  /**
   * Short author bio for blog articles
   */
  bio?: string | null;
  /**
   * Job title or role displayed on blog articles
   */
  jobTitle?: string | null;
  role: 'admin' | 'editor' | 'guest';
  emailVerified?: boolean | null;
  image?: string | null;
  twoFactorEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Remove audio track from the video during optimization
   */
  stripAudio?: boolean | null;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  hero?:
    | (
        | {
            mediaSrc: number | Media;
            /**
             * Still image shown while a video loads. Upload a frame from the video for best results.
             */
            posterSrc?: (number | null) | Media;
            headline: string;
            subtext: string;
            primaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('default' | 'outline') | null;
              buttonSize?: 'lg' | null;
            };
            secondaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('outline' | 'default') | null;
              buttonSize?: 'lg' | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            mediaSrc: number | Media;
            /**
             * Still image shown while a video loads.
             */
            posterSrc?: (number | null) | Media;
            headline: string;
            subtext: string;
            primaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('default' | 'outline') | null;
              buttonSize?: 'lg' | null;
            };
            secondaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('outline' | 'default') | null;
              buttonSize?: 'lg' | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroCentered';
          }
        | {
            headline: string;
            subtext: string;
            /**
             * Stats displayed in a grid panel. Leave empty and provide media instead.
             */
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Shown when no stats are provided. Optional if stats are populated.
             */
            mediaSrc?: (number | null) | Media;
            /**
             * Still image shown while a video loads.
             */
            posterSrc?: (number | null) | Media;
            primaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('default' | 'outline') | null;
              buttonSize?: 'lg' | null;
            };
            secondaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('outline' | 'default') | null;
              buttonSize?: 'lg' | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroStats';
          }
        | {
            headline: string;
            subtext: string;
            primaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('default' | 'outline') | null;
              buttonSize?: 'lg' | null;
            };
            secondaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('outline' | 'default') | null;
              buttonSize?: 'lg' | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroMinimal';
          }
      )[]
    | null;
  layout?:
    | (
        | {
            headline: string;
            subtext: string;
            image: {
              src: number | Media;
              alt: string;
              title: string;
              description: string;
              badge?: string | null;
            };
            showcase: {
              src: number | Media;
              alt: string;
              title: string;
              description: string;
              badge?: string | null;
            };
            chartData?:
              | {
                  month: string;
                  visitors: number;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bento';
          }
        | {
            rows: {
              headline: string;
              body: string;
              mediaLabel: string;
              mediaSrc: number | Media;
              mediaAlt: string;
              cta?: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                url?: string | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                label?: string | null;
                /**
                 * Choose how the link should be rendered.
                 */
                appearanceType?: 'link' | null;
                linkVariant?: ('arrow' | 'plain') | null;
              };
              mediaOverlay: {
                title: string;
                badge?: string | null;
                description: string;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitMedia';
          }
        | {
            headline: string;
            subtext: string;
            testimonials: {
              name: string;
              role: string;
              department: string;
              quote: string;
              avatar?: (number | null) | Media;
              featured?: boolean | null;
              featuredQuote?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            items: {
              label: string;
              caption: string;
              image: number | Media;
              imageAlt: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            headline: string;
            subtext: string;
            /**
             * Number of articles to display (default: 5)
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestArticles';
          }
        | {
            videoSrc: number | Media;
            label: string;
            headline: string;
            subtext: string;
            cta?: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label?: string | null;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('default' | 'outline') | null;
              buttonSize?: 'lg' | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cinematicCta';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            subtext?: string | null;
            variant?: ('primary' | 'card') | null;
            primaryCta: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('default' | 'outline') | null;
              buttonSize?: ('default' | 'lg') | null;
            };
            secondaryCta?: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label?: string | null;
              /**
               * Choose how the link should be rendered.
               */
              appearanceType?: 'button' | null;
              buttonVariant?: ('outline' | 'default') | null;
              buttonSize?: ('default' | 'lg') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBand';
          }
        | {
            headline: string;
            subtext: string;
            footnote?: string | null;
            footnoteAttribution?: string | null;
            tiers: {
              name: string;
              description: string;
              monthlyPrice: number;
              annualPrice: number;
              features?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              cta: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                url?: string | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                label: string;
                /**
                 * Choose how the link should be rendered.
                 */
                appearanceType?: 'button' | null;
                buttonVariant?: ('default' | 'outline') | null;
                buttonSize?: 'lg' | null;
              };
              badge?: string | null;
              recommended?: boolean | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            subtext?: string | null;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            ctaText?: string | null;
            cta?: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            items?:
              | {
                  icon?:
                    | (
                        | 'layers'
                        | 'shieldCheck'
                        | 'lightning'
                        | 'lock'
                        | 'chart'
                        | 'sync'
                        | 'globe'
                        | 'code'
                        | 'database'
                        | 'cpu'
                        | 'users'
                        | 'settings'
                      )
                    | null;
                  label?: string | null;
                  heading: string;
                  description: string;
                  link?: {
                    type?: ('internal' | 'external') | null;
                    newTab?: boolean | null;
                    url?: string | null;
                    reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                    } | null;
                    label?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuresGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            variant?: ('detailed' | 'compact') | null;
            members?:
              | {
                  photo?: (number | null) | Media;
                  name: string;
                  role: string;
                  department?: string | null;
                  bio?: string | null;
                  links?:
                    | {
                        platform?: ('linkedin' | 'twitter' | 'github' | 'website') | null;
                        url: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            eyebrow?: string | null;
            stats: {
              label: string;
              value: number;
              decimals?: number | null;
              format?: ('none' | 'k') | null;
              suffix?: string | null;
              id?: string | null;
            }[];
            logos?:
              | {
                  name: string;
                  logo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trust';
          }
        | {
            eyebrow?: string | null;
            variant?: ('scroll' | 'grid') | null;
            logos?:
              | {
                  logo: number | Media;
                  name: string;
                  link?: {
                    type?: ('internal' | 'external') | null;
                    newTab?: boolean | null;
                    url?: string | null;
                    reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                    } | null;
                    label?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoCloud';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            maxWidth?: ('narrow' | 'default' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextContent';
          }
        | {
            eyebrow?: string | null;
            stats: {
              value: string;
              label: string;
              description?: string | null;
              id?: string | null;
            }[];
            variant?: ('default' | 'card' | 'minimal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsBar';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            partners: {
              logo?: (number | null) | Media;
              name: string;
              description?: string | null;
              link?: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                url?: string | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                label?: string | null;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            items: {
              date: string;
              heading: string;
              description: string;
              stat?: string | null;
              statLabel?: string | null;
              category?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            tabs: {
              label: string;
              heading: string;
              description: string;
              image?: (number | null) | Media;
              icon?:
                | (
                    | 'layers'
                    | 'shieldCheck'
                    | 'lightning'
                    | 'lock'
                    | 'chart'
                    | 'sync'
                    | 'globe'
                    | 'code'
                    | 'database'
                    | 'cpu'
                    | 'users'
                    | 'settings'
                  )
                | null;
              features?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabbedContent';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            features: {
              name: string;
              tooltip?: string | null;
              category?: string | null;
              id?: string | null;
            }[];
            plans: {
              name: string;
              price?: string | null;
              description?: string | null;
              recommended?: boolean | null;
              cta: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                url?: string | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                label: string;
                /**
                 * Choose how the link should be rendered.
                 */
                appearanceType?: 'button' | null;
                buttonVariant?: ('default' | 'outline') | null;
                buttonSize?: ('default' | 'lg') | null;
              };
              values: {
                featureIndex: number;
                value?: ('included' | 'excluded' | 'partial' | 'text') | null;
                textValue?: string | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparisonTable';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            jobs: {
              title: string;
              department: string;
              location: string;
              type?: ('full-time' | 'part-time' | 'contract' | 'internship') | null;
              salary?: string | null;
              description?: string | null;
              link: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                url?: string | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                label: string;
                /**
                 * Choose how the link should be rendered.
                 */
                appearanceType?: 'button' | null;
                buttonVariant?: ('default' | 'outline') | null;
                buttonSize?: ('default' | 'lg') | null;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'jobListings';
          }
        | {
            variant: 'stacked' | 'split' | 'map';
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            form: number | Form;
            mapCenter?: {
              latitude: number;
              longitude: number;
            };
            mapZoom?: number | null;
            /**
             * Popup text shown when the map pin is clicked
             */
            mapMarkerLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formEmbed';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    robots?: {
      /**
       * Enable to set custom robots directives for this page.
       */
      override?: boolean | null;
      index?: boolean | null;
      follow?: boolean | null;
    };
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Hide this page from the sitemap. It can still be indexed if linked to externally.
     */
    excludeFromSitemap?: boolean | null;
  };
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Select a parent page to nest this page under
   */
  parent?: (number | null) | Page;
  /**
   * Auto-computed URL path (e.g., divisions/macrodata-refinement)
   */
  path?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  heroImage: number | Media;
  /**
   * Short summary for cards and SEO fallback
   */
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    robots?: {
      /**
       * Enable to set custom robots directives for this page.
       */
      override?: boolean | null;
      index?: boolean | null;
      follow?: boolean | null;
    };
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Hide this page from the sitemap. It can still be indexed if linked to externally.
     */
    excludeFromSitemap?: boolean | null;
  };
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  category: number | Category;
  author: number | User;
  publishedAt: string;
  /**
   * Auto-calculated from body content (minutes)
   */
  readTime?: number | null;
  /**
   * Override author display details for this article
   */
  showAuthorOverride?: boolean | null;
  authorOverride?: {
    displayName?: string | null;
    avatar?: (number | null) | Media;
    bio?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ba-sessions".
 */
export interface BaSession {
  id: number;
  token: string;
  userId: number;
  expiresAt: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ba-accounts".
 */
export interface BaAccount {
  id: number;
  accountId: string;
  providerId: string;
  userId: number;
  accessToken?: string | null;
  refreshToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  password?: string | null;
  idToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ba-verifications".
 */
export interface BaVerification {
  id: number;
  identifier: string;
  value: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ba-two-factors".
 */
export interface BaTwoFactor {
  id: number;
  secret: string;
  backupCodes?: string | null;
  userId: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  articles?: {
    /**
     * Allow clients to find articles.
     */
    find?: boolean | null;
    /**
     * Allow clients to create articles.
     */
    create?: boolean | null;
    /**
     * Allow clients to update articles.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete articles.
     */
    delete?: boolean | null;
  };
  forms?: {
    /**
     * Allow clients to find forms.
     */
    find?: boolean | null;
    /**
     * Allow clients to create forms.
     */
    create?: boolean | null;
    /**
     * Allow clients to update forms.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete forms.
     */
    delete?: boolean | null;
  };
  formSubmissions?: {
    /**
     * Allow clients to find form-submissions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create form-submissions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update form-submissions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete form-submissions.
     */
    delete?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Returns available hero block types (max 1 per page) with slugs, labels, and descriptions. Use when choosing a hero variant for a page.
     */
    listHeroBlocks?: boolean | null;
    /**
     * Returns available content/layout block types with slugs, labels, and descriptions. Use when building a page's content sections.
     */
    listContentBlocks?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'optimizeVideo';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'optimizeVideo') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'ba-sessions';
        value: number | BaSession;
      } | null)
    | ({
        relationTo: 'ba-accounts';
        value: number | BaAccount;
      } | null)
    | ({
        relationTo: 'ba-verifications';
        value: number | BaVerification;
      } | null)
    | ({
        relationTo: 'ba-two-factors';
        value: number | BaTwoFactor;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  bio?: T;
  jobTitle?: T;
  role?: T;
  emailVerified?: T;
  image?: T;
  twoFactorEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  stripAudio?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero?:
          | T
          | {
              mediaSrc?: T;
              posterSrc?: T;
              headline?: T;
              subtext?: T;
              primaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              secondaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroCentered?:
          | T
          | {
              mediaSrc?: T;
              posterSrc?: T;
              headline?: T;
              subtext?: T;
              primaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              secondaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroStats?:
          | T
          | {
              headline?: T;
              subtext?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              mediaSrc?: T;
              posterSrc?: T;
              primaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              secondaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroMinimal?:
          | T
          | {
              headline?: T;
              subtext?: T;
              primaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              secondaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  layout?:
    | T
    | {
        bento?:
          | T
          | {
              headline?: T;
              subtext?: T;
              image?:
                | T
                | {
                    src?: T;
                    alt?: T;
                    title?: T;
                    description?: T;
                    badge?: T;
                  };
              showcase?:
                | T
                | {
                    src?: T;
                    alt?: T;
                    title?: T;
                    description?: T;
                    badge?: T;
                  };
              chartData?:
                | T
                | {
                    month?: T;
                    visitors?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitMedia?:
          | T
          | {
              rows?:
                | T
                | {
                    headline?: T;
                    body?: T;
                    mediaLabel?: T;
                    mediaSrc?: T;
                    mediaAlt?: T;
                    cta?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          url?: T;
                          reference?: T;
                          label?: T;
                          appearanceType?: T;
                          linkVariant?: T;
                        };
                    mediaOverlay?:
                      | T
                      | {
                          title?: T;
                          badge?: T;
                          description?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              headline?: T;
              subtext?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    role?: T;
                    department?: T;
                    quote?: T;
                    avatar?: T;
                    featured?: T;
                    featuredQuote?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    caption?: T;
                    image?: T;
                    imageAlt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        latestArticles?:
          | T
          | {
              headline?: T;
              subtext?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        cinematicCta?:
          | T
          | {
              videoSrc?: T;
              label?: T;
              headline?: T;
              subtext?: T;
              cta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              variant?: T;
              primaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              secondaryCta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                    appearanceType?: T;
                    buttonVariant?: T;
                    buttonSize?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              headline?: T;
              subtext?: T;
              footnote?: T;
              footnoteAttribution?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    description?: T;
                    monthlyPrice?: T;
                    annualPrice?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    cta?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          url?: T;
                          reference?: T;
                          label?: T;
                          appearanceType?: T;
                          buttonVariant?: T;
                          buttonSize?: T;
                        };
                    badge?: T;
                    recommended?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              ctaText?: T;
              cta?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featuresGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    heading?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          url?: T;
                          reference?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              variant?: T;
              members?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    role?: T;
                    department?: T;
                    bio?: T;
                    links?:
                      | T
                      | {
                          platform?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        trust?:
          | T
          | {
              eyebrow?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    decimals?: T;
                    format?: T;
                    suffix?: T;
                    id?: T;
                  };
              logos?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              eyebrow?: T;
              variant?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          url?: T;
                          reference?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richTextContent?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
        statsBar?:
          | T
          | {
              eyebrow?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        partnerGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              partners?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          url?: T;
                          reference?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    date?: T;
                    heading?: T;
                    description?: T;
                    stat?: T;
                    statLabel?: T;
                    category?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tabbedContent?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    heading?: T;
                    description?: T;
                    image?: T;
                    icon?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparisonTable?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              features?:
                | T
                | {
                    name?: T;
                    tooltip?: T;
                    category?: T;
                    id?: T;
                  };
              plans?:
                | T
                | {
                    name?: T;
                    price?: T;
                    description?: T;
                    recommended?: T;
                    cta?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          url?: T;
                          reference?: T;
                          label?: T;
                          appearanceType?: T;
                          buttonVariant?: T;
                          buttonSize?: T;
                        };
                    values?:
                      | T
                      | {
                          featureIndex?: T;
                          value?: T;
                          textValue?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        jobListings?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              jobs?:
                | T
                | {
                    title?: T;
                    department?: T;
                    location?: T;
                    type?: T;
                    salary?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          url?: T;
                          reference?: T;
                          label?: T;
                          appearanceType?: T;
                          buttonVariant?: T;
                          buttonSize?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        formEmbed?:
          | T
          | {
              variant?: T;
              heading?: T;
              content?: T;
              form?: T;
              mapCenter?:
                | T
                | {
                    latitude?: T;
                    longitude?: T;
                  };
              mapZoom?: T;
              mapMarkerLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        robots?:
          | T
          | {
              override?: T;
              index?: T;
              follow?: T;
            };
        keywords?: T;
        excludeFromSitemap?: T;
      };
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  path?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  heroImage?: T;
  excerpt?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        robots?:
          | T
          | {
              override?: T;
              index?: T;
              follow?: T;
            };
        keywords?: T;
        excludeFromSitemap?: T;
      };
  title?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  showAuthorOverride?: T;
  authorOverride?:
    | T
    | {
        displayName?: T;
        avatar?: T;
        bio?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ba-sessions_select".
 */
export interface BaSessionsSelect<T extends boolean = true> {
  token?: T;
  userId?: T;
  expiresAt?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ba-accounts_select".
 */
export interface BaAccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  userId?: T;
  accessToken?: T;
  refreshToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  idToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ba-verifications_select".
 */
export interface BaVerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ba-two-factors_select".
 */
export interface BaTwoFactorsSelect<T extends boolean = true> {
  secret?: T;
  backupCodes?: T;
  userId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  articles?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  forms?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  formSubmissions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        listHeroBlocks?: T;
        listContentBlocks?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Full URL without trailing slash (e.g. https://lumon.dev)
   */
  baseUrl: string;
  /**
   * Character(s) between page title and site name
   */
  separator?: string | null;
  /**
   * Fallback social share image when a page has no meta image. Must be a raster image (no SVGs or videos).
   */
  defaultOgImage?: (number | null) | Media;
  robots?: {
    index?: boolean | null;
    follow?: boolean | null;
  };
  social?: {
    /**
     * @handle for twitter:site tag
     */
    twitter?: string | null;
    twitterCardType?: ('summary' | 'summary_large_image') | null;
  };
  jsonLd?: {
    organizationName?: string | null;
    organizationLogo?: (number | null) | Media;
    organizationUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: {
    type?: ('text' | 'image') | null;
    /**
     * Primary text (e.g. 'Lumon')
     */
    text?: string | null;
    /**
     * Secondary styled text (e.g. 'Payload')
     */
    textAccent?: string | null;
    image?: (number | null) | Media;
    /**
     * Max height in pixels (e.g. 32)
     */
    imageHeight?: number | null;
  };
  navItems?:
    | (
        | {
            link: {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              url?: string | null;
              reference?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              label: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'direct-link';
          }
        | {
            /**
             * Text shown in the navbar (e.g. 'Resources')
             */
            label: string;
            items?:
              | {
                  link: {
                    type?: ('internal' | 'external') | null;
                    newTab?: boolean | null;
                    url?: string | null;
                    reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                    } | null;
                    label: string;
                  };
                  icon?:
                    | (
                        | 'analytics-up'
                        | 'brain'
                        | 'camera-video'
                        | 'chart'
                        | 'dna'
                        | 'file'
                        | 'heart-check'
                        | 'labor'
                        | 'mail'
                        | 'microscope'
                        | 'news'
                        | 'shield'
                        | 'user-group'
                        | 'user'
                        | 'bar-chart'
                        | 'code'
                        | 'cpu'
                        | 'database'
                        | 'flash'
                        | 'globe'
                        | 'layers'
                        | 'lock'
                        | 'sync'
                        | 'settings'
                        | 'shield-01'
                        | 'cloud'
                        | 'dashboard'
                        | 'headphones'
                        | 'laptop'
                        | 'search'
                        | 'arrow-right'
                        | 'bookmark'
                        | 'calendar'
                        | 'call'
                        | 'check'
                        | 'clock'
                        | 'download'
                        | 'link'
                        | 'location'
                        | 'puzzle'
                        | 'rocket'
                        | 'star'
                        | 'tag'
                        | 'upload'
                        | 'zap'
                      )
                    | null;
                  /**
                   * Short description shown below the link
                   */
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dropdown';
          }
        | {
            /**
             * Text shown in the navbar (e.g. 'Divisions')
             */
            label: string;
            groups?:
              | {
                  /**
                   * Column heading (e.g. 'Core Operations')
                   */
                  groupLabel: string;
                  items?:
                    | {
                        link: {
                          type?: ('internal' | 'external') | null;
                          newTab?: boolean | null;
                          url?: string | null;
                          reference?: {
                            relationTo: 'pages';
                            value: number | Page;
                          } | null;
                          label: string;
                        };
                        icon?:
                          | (
                              | 'analytics-up'
                              | 'brain'
                              | 'camera-video'
                              | 'chart'
                              | 'dna'
                              | 'file'
                              | 'heart-check'
                              | 'labor'
                              | 'mail'
                              | 'microscope'
                              | 'news'
                              | 'shield'
                              | 'user-group'
                              | 'user'
                              | 'bar-chart'
                              | 'code'
                              | 'cpu'
                              | 'database'
                              | 'flash'
                              | 'globe'
                              | 'layers'
                              | 'lock'
                              | 'sync'
                              | 'settings'
                              | 'shield-01'
                              | 'cloud'
                              | 'dashboard'
                              | 'headphones'
                              | 'laptop'
                              | 'search'
                              | 'arrow-right'
                              | 'bookmark'
                              | 'calendar'
                              | 'call'
                              | 'check'
                              | 'clock'
                              | 'download'
                              | 'link'
                              | 'location'
                              | 'puzzle'
                              | 'rocket'
                              | 'star'
                              | 'tag'
                              | 'upload'
                              | 'zap'
                            )
                          | null;
                        description?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mega-menu';
          }
      )[]
    | null;
  cta?: {
    show?: boolean | null;
    link?: {
      type?: ('internal' | 'external') | null;
      newTab?: boolean | null;
      url?: string | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      label?: string | null;
      /**
       * Choose how the link should be rendered.
       */
      appearanceType?: 'button' | null;
      buttonVariant?: ('default' | 'outline' | 'secondary') | null;
      buttonSize?: ('sm' | 'default' | 'lg') | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: {
    type?: ('text' | 'image') | null;
    /**
     * Primary text (e.g. 'Lumon')
     */
    text?: string | null;
    /**
     * Secondary styled text (e.g. 'Payload')
     */
    textAccent?: string | null;
    image?: (number | null) | Media;
    /**
     * Max height in pixels (e.g. 32)
     */
    imageHeight?: number | null;
  };
  /**
   * Short tagline below the logo
   */
  tagline?: string | null;
  columns?:
    | {
        label: string;
        links?:
          | {
              link: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                url?: string | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'github' | 'twitter' | 'linkedin' | 'instagram' | 'youtube' | 'facebook' | 'tiktok' | 'discord';
        /**
         * Full URL to your profile
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        link: {
          type?: ('internal' | 'external') | null;
          newTab?: boolean | null;
          url?: string | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Company name for copyright line. Year is auto-generated.
   */
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  baseUrl?: T;
  separator?: T;
  defaultOgImage?: T;
  robots?:
    | T
    | {
        index?: T;
        follow?: T;
      };
  social?:
    | T
    | {
        twitter?: T;
        twitterCardType?: T;
      };
  jsonLd?:
    | T
    | {
        organizationName?: T;
        organizationLogo?: T;
        organizationUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        type?: T;
        text?: T;
        textAccent?: T;
        image?: T;
        imageHeight?: T;
      };
  navItems?:
    | T
    | {
        'direct-link'?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dropdown?:
          | T
          | {
              label?: T;
              items?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          url?: T;
                          reference?: T;
                          label?: T;
                        };
                    icon?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'mega-menu'?:
          | T
          | {
              label?: T;
              groups?:
                | T
                | {
                    groupLabel?: T;
                    items?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                url?: T;
                                reference?: T;
                                label?: T;
                              };
                          icon?: T;
                          description?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  cta?:
    | T
    | {
        show?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              url?: T;
              reference?: T;
              label?: T;
              appearanceType?: T;
              buttonVariant?: T;
              buttonSize?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        type?: T;
        text?: T;
        textAccent?: T;
        image?: T;
        imageHeight?: T;
      };
  tagline?: T;
  columns?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    url?: T;
                    reference?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              url?: T;
              reference?: T;
              label?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskOptimizeVideo".
 */
export interface TaskOptimizeVideo {
  input: {
    mediaId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}